site_name: 高中学习与生活质量指北
site_url: https://vic2349.github.io/senior-school-guide/  # 添加这行

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
  palette:
    primary: indigo
    accent: blue

extra:
  include:
    - .nojekyll
  exclude: 
    - .github/  

nav:
  - 首页: index.md
#  - 择校相关:
#      - 页面一: page1.md  # 增加缩进
#      - 页面二: page2.md  # 增加缩进
#  - 问卷数据:
#    - 湖北:
      - 武汉市:
        - 武汉市第十六中学: 
        - 武汉市民族中学: 
        - 武汉市第二十中学: 
        - 武汉市第二中学: 
        - 武汉市实验学校: 
        - 武汉市育才高级中学: 
        - 武汉育才美术高级中学: 
        - 武汉市第六中学: 
        - 武汉市第十九中学: 
        - 武汉外国语学校: 
        - 武汉市第一中学: 
        - 武汉市第七中学: 
        - 武汉市第十二中学: 
        - 武汉市常青第一中学: 
        - 武汉市第六十八中学: 
        - 武汉外国语学校美加分校:
        - 武汉青云中学:
        - 空军武汉少年军校:
        - 武汉市第二十六中学:
        - 武汉市第十一中学:
        - 武汉市第四中学:
        - 武汉市太平洋高级中学:
        - 武汉市第四十三中学:
        - 武汉市第二十九中学:
        - 武汉市第十七中学:
        - 武汉英中高级中学:
        - 武汉市弘桥中学:
        - 武汉市建港中学:
        - 武汉情智学校:
        - 武汉市第二十三中学:
        - 武汉市第三中学:
        - 武汉市晴川高级中学:
        - 武昌文华中学:
        - 湖北省水果湖高级中学: schools/hu-bei-sheng-shui-guo-hu-gao-ji-zhong-xue.md
        - 华中师范大学第一附属中学:
        - 武汉市东湖中学:
        - 武汉市第三十九中学:
        - 武汉市第十五中学:
        - 湖北省武昌实验中学:
        - 武汉市第十四中学:
        - 湖北大学附属中学:
        - 武汉中学:
        - 武汉市武钢三中:
        - 武汉市第四十九中学:
        - 武汉市钢城第四中学:
        - 武汉思久高级中学:
        - 武汉市钢城第十六中学:
        - 武汉市钢都中学:
        - 武汉市钢城第十四中学:
        - 武汉成丰学校:
        - 武汉大学附属中学:
        - 武汉澳新高级中学:
        - 武汉市关山中学:
        - 武汉市马房山中学:
        - 武汉市长虹中学:
        - 武汉市洪山高级中学:
        - 武汉西藏中学:
        - 武汉经济技术开发区汉阳三中:
        - 武汉经济技术开发区第一中学:
        - 武汉三牛中美中学:
        - 武汉经开外国语高级中学:
        - 武汉爱莎文华高级中学有限公司:
        - 武汉光谷（国际）外国语学校:
        - 华中师范大学第一附属中学光谷分校:
        - 武汉东湖新技术开发区点睛学校:
        - 武汉市光谷第二高级中学:
        - 华中科技大学附属中学:
        - 武昌实验寄宿学校:
        - 武汉崇文高级中学:
        - 武汉市吴家山第四中学:
        - 武汉睿升学校:
        - 武汉市吴家山中学:
        - 武汉为明高级中学:
        - 武汉市汉南第一中学:
        - 武汉市汉南第二中学:
        - 武汉市蔡甸区汉阳一中:
        - 武汉市蔡甸区实验高级中学:
        - 武汉枫叶国际学校:
        - 武汉精英学校:
        - 武汉市蔡甸区汉阳二中:
        - 武汉市蔡甸区第四中学校:
        - 武汉海淀外国语实验学校:
        - 武汉市江夏区五里界中学:
        - 武汉藏龙高级中学:
        - 武汉市江夏区第一中学:
        - 武汉市江夏区实验高级中学:
        - 武汉市江夏区金口中学:
        - 武汉市江夏区山坡中学:
        - 武汉市黄陂区第二中学:
        - 武汉市黄陂区第三中学:
        - 武汉市黄陂区第七中学:
        - 武汉市黄陂区第六中学:
        - 武汉市黄陂区第一中学:
        - 武汉市汉口北高级中学:
        - 武汉康礼高级中学有限公司:
        - 武汉市新洲区第一中学:
        - 武汉市新洲区第二中学:
        - 武汉市新洲区第三中学:
        - 武汉市新洲区第四中学:
        - 武汉市新洲区城关高级中学:
        - 武汉市新洲区阳逻高级中学:
