site_name: 高中学习与生活质量指北
site_url: https://vic2349.github.io/senior-school-guide/  # 添加这行

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
  palette:
    primary: indigo
    accent: blue

extra:
  include:
    - .nojekyll
  exclude: 
    - .github/  

nav:
  - 首页: index.md
#  - 择校相关:
#      - 页面一: page1.md  # 增加缩进
#      - 页面二: page2.md  # 增加缩进
  - 问卷数据:
    - 湖北:
      - 武汉市:
        - 武汉外国语学校: schools/wu-han-wai-guo-yu-xue-xiao.md
        - 湖北省水果湖高级中学: schools/hu-bei-sheng-shui-guo-hu-gao-ji-zhong-xue.md
        - 湖北省武昌实验中学: schools/hu-bei-sheng-wu-chang-shi-yan-zhong-xue.md
        - 武汉市第十四中学: schools/wu-han-shi-di-shi-si-zhong-xue.md
        - 武汉中学: schools/wu-han-zhong-xue.md
        
