site_name: 高中学习与生活质量指北
site_url: https://619.edu.deal/  # 添加这行

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github  # 使用 FontAwesome 的 GitHub 图标
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.action.edit  # 强制显示编辑按钮（某些版本需要）
  palette:
    primary: indigo
    accent: cyan
  language: zh 
  plugins:
  - search

repo_url: https://github.com/vic2349/senior-school-guide
repo_name: vic2349/senior-school-guide

edit_uri: edit/gh-pages/docs/

extra:
  include:
    - .nojekyll
  exclude: 
    - .github/  

nav:
  - 首页: index.md
#  - 择校相关:
#      - 页面一: page1.md  # 增加缩进
#      - 页面二: page2.md  # 增加缩进
  - 问卷数据:
    - 湖北:
      - 武汉市:
        - 武汉市第十六中学: schools/wu-han-shi-di-shi-liu-zhong-xue.md
        - 武汉市民族中学: schools/wu-han-shi-min-zu-zhong-xue.md
        - 武汉市第二十中学: schools/wu-han-shi-di-er-shi-zhong-xue.md
        - 武汉市第二中学: schools/wu-han-shi-di-er-zhong-xue.md
        - 武汉市汉铁高级中学: schools/wu-han-shi-han-tie-gao-ji-zhong-xue.md
        - 武汉市实验学校: schools/wu-han-shi-shi-yan-xue-xiao.md
        - 武汉市育才高级中学: schools/wu-han-shi-yu-cai-gao-ji-zhong-xue.md
        - 武汉育才美术高级中学: schools/wu-han-yu-cai-mei-shu-gao-ji-zhong-xue.md
        - 武汉市第六中学: schools/wu-han-shi-di-liu-zhong-xue.md
        - 武汉市第十九中学: schools/wu-han-shi-di-shi-jiu-zhong-xue.md
        - 武汉外国语学校: schools/wu-han-wai-guo-yu-xue-xiao.md
        - 武汉市第一中学: schools/wu-han-shi-di-yi-zhong-xue.md
        - 武汉市第七中学: schools/wu-han-shi-di-qi-zhong-xue.md
        - 武汉市第十二中学: schools/wu-han-shi-di-shi-er-zhong-xue.md
        - 武汉市常青第一中学: schools/wu-han-shi-chang-qing-di-yi-zhong-xue.md
        - 武汉市第六十八中学: schools/wu-han-shi-di-liu-shi-ba-zhong-xue.md
        - 武汉外国语学校美加分校: schools/wu-han-wai-guo-yu-xue-xiao-mei-jia-fen-xiao.md
        - 武汉青云中学: schools/wu-han-qing-yun-zhong-xue.md
        - 空军武汉少年军校: schools/kong-jun-wu-han-shao-nian-jun-xiao.md
        - 武汉市第二十六中学: schools/wu-han-shi-di-er-shi-liu-zhong-xue.md
        - 武汉市第十一中学: schools/wu-han-shi-di-shi-yi-zhong-xue.md
        - 武汉市第四中学: schools/wu-han-shi-di-si-zhong-xue.md
        - 武汉市太平洋高级中学: schools/wu-han-shi-tai-ping-yang-gao-ji-zhong-xue.md
        - 武汉市第四十三中学: schools/wu-han-shi-di-si-shi-san-zhong-xue.md
        - 武汉市第二十九中学: schools/wu-han-shi-di-er-shi-jiu-zhong-xue.md
        - 武汉市第十七中学: schools/wu-han-shi-di-shi-qi-zhong-xue.md
        - 武汉英中高级中学: schools/wu-han-ying-zhong-gao-ji-zhong-xue.md
        - 武汉市弘桥中学: schools/wu-han-shi-hong-qiao-zhong-xue.md
        - 武汉市建港中学: schools/wu-han-shi-jian-gang-zhong-xue.md
        - 武汉情智学校: schools/wu-han-qing-zhi-xue-xiao.md
        - 武汉市第二十三中学: schools/wu-han-shi-di-er-shi-san-zhong-xue.md
        - 武汉市第三中学: schools/wu-han-shi-di-san-zhong-xue.md
        - 武汉市晴川高级中学: schools/wu-han-shi-qing-chuan-gao-ji-zhong-xue.md
        - 武昌文华中学: schools/wu-chang-wen-hua-zhong-xue.md
        - 湖北省水果湖高级中学: schools/hu-bei-sheng-shui-guo-hu-gao-ji-zhong-xue.md
        - 华中师范大学第一附属中学: schools/hua-zhong-shi-fan-da-xue-di-yi-fu-shu-zhong-xue.md
        - 武汉市东湖中学: schools/wu-han-shi-dong-hu-zhong-xue.md
        - 武汉市第三十九中学: schools/wu-han-shi-di-san-shi-jiu-zhong-xue.md
        - 武汉市第十五中学: schools/wu-han-shi-di-shi-wu-zhong-xue.md
        - 湖北省武昌实验中学: schools/hu-bei-sheng-wu-chang-shi-yan-zhong-xue.md
        - 武汉市第十四中学: schools/wu-han-shi-di-shi-si-zhong-xue.md
        - 湖北大学附属中学: schools/hu-bei-da-xue-fu-shu-zhong-xue.md
        - 武汉中学: schools/wu-han-zhong-xue.md
        - 武汉市武钢三中: schools/wu-han-shi-wu-gang-san-zhong.md
        - 武汉市第四十九中学: schools/wu-han-shi-di-si-shi-jiu-zhong-xue.md
        - 武汉市钢城第四中学: schools/wu-han-shi-gang-cheng-di-si-zhong-xue.md
        - 武汉思久高级中学: schools/wu-han-si-jiu-gao-ji-zhong-xue.md
        - 武汉市钢城第十六中学: schools/wu-han-shi-gang-cheng-di-shi-liu-zhong-xue.md
        - 武汉市钢都中学: schools/wu-han-shi-gang-du-zhong-xue.md
        - 武汉市钢城第十四中学: schools/wu-han-shi-gang-cheng-di-shi-si-zhong-xue.md
        - 武汉成丰学校: schools/wu-han-cheng-feng-xue-xiao.md
        - 武汉大学附属中学: schools/wu-han-da-xue-fu-shu-zhong-xue.md
        - 武汉澳新高级中学: schools/wu-han-ao-xin-gao-ji-zhong-xue.md
        - 武汉市关山中学: schools/wu-han-shi-guan-shan-zhong-xue.md
        - 武汉市马房山中学: schools/wu-han-shi-ma-fang-shan-zhong-xue.md
        - 武汉市长虹中学: schools/wu-han-shi-chang-hong-zhong-xue.md
        - 武汉市洪山高级中学: schools/wu-han-shi-hong-shan-gao-ji-zhong-xue.md
        - 武汉西藏中学: schools/wu-han-xi-zang-zhong-xue.md
        - 武汉经济技术开发区汉阳三中: schools/wu-han-jing-ji-ji-shu-kai-fa-qu-han-yang-san-zhong.md
        - 武汉经济技术开发区第一中学: schools/wu-han-jing-ji-ji-shu-kai-fa-qu-di-yi-zhong-xue.md
        - 武汉三牛中美中学: schools/wu-han-san-niu-zhong-mei-zhong-xue.md
        - 武汉经开外国语高级中学: schools/wu-han-jing-kai-wai-guo-yu-gao-ji-zhong-xue.md
        - 武汉爱莎文华高级中学有限公司: schools/wu-han-ai-sha-wen-hua-gao-ji-zhong-xue-you-xian-gong-si.md
        - 武汉光谷（国际）外国语学校: schools/wu-han-guang-gu-guo-ji-wai-guo-yu-xue-xiao.md
        - 华中师范大学第一附属中学光谷分校: schools/hua-zhong-shi-fan-da-xue-di-yi-fu-shu-zhong-xue-guang-gu-fen-xiao.md
        - 武汉东湖新技术开发区点睛学校: schools/wu-han-dong-hu-xin-ji-shu-kai-fa-qu-dian-jing-xue-xiao.md
        - 武汉市光谷第二高级中学: schools/wu-han-shi-guang-gu-di-er-gao-ji-zhong-xue.md
        - 华中科技大学附属中学: schools/hua-zhong-ke-ji-da-xue-fu-shu-zhong-xue.md
        - 武昌实验寄宿学校: schools/wu-chang-shi-yan-ji-su-xue-xiao.md
        - 武汉崇文高级中学: schools/wu-han-chong-wen-gao-ji-zhong-xue.md
        - 武汉市吴家山第四中学: schools/wu-han-shi-wu-jia-shan-di-si-zhong-xue.md
        - 武汉睿升学校: schools/wu-han-rui-sheng-xue-xiao.md
        - 武汉市吴家山中学: schools/wu-han-shi-wu-jia-shan-zhong-xue.md
        - 武汉为明高级中学: schools/wu-han-wei-ming-gao-ji-zhong-xue.md
        - 武汉市汉南第一中学: schools/wu-han-shi-han-nan-di-yi-zhong-xue.md
        - 武汉市汉南第二中学: schools/wu-han-shi-han-nan-di-er-zhong-xue.md
        - 武汉市蔡甸区汉阳一中: schools/wu-han-shi-cai-dian-qu-han-yang-yi-zhong.md
        - 武汉市蔡甸区实验高级中学: schools/wu-han-shi-cai-dian-qu-shi-yan-gao-ji-zhong-xue.md
        - 武汉枫叶国际学校: schools/wu-han-feng-ye-guo-ji-xue-xiao.md
        - 武汉精英学校: schools/wu-han-jing-ying-xue-xiao.md
        - 武汉市蔡甸区汉阳二中: schools/wu-han-shi-cai-dian-qu-han-yang-er-zhong.md
        - 武汉市蔡甸区第四中学校: schools/wu-han-shi-cai-dian-qu-di-si-zhong-xue-xiao.md
        - 武汉海淀外国语实验学校: schools/wu-han-hai-dian-wai-guo-yu-shi-yan-xue-xiao.md
        - 武汉市江夏区五里界中学: schools/wu-han-shi-jiang-xia-qu-wu-li-jie-zhong-xue.md
        - 武汉藏龙高级中学: schools/wu-han-cang-long-gao-ji-zhong-xue.md
        - 武汉市江夏区第一中学: schools/wu-han-shi-jiang-xia-qu-di-yi-zhong-xue.md
        - 武汉市江夏区实验高级中学: schools/wu-han-shi-jiang-xia-qu-shi-yan-gao-ji-zhong-xue.md
        - 武汉市江夏区金口中学: schools/wu-han-shi-jiang-xia-qu-jin-kou-zhong-xue.md
        - 武汉市江夏区山坡中学: schools/wu-han-shi-jiang-xia-qu-shan-po-zhong-xue.md
        - 武汉市黄陂区第二中学: schools/wu-han-shi-huang-pi-qu-di-er-zhong-xue.md
        - 武汉市黄陂区第三中学: schools/wu-han-shi-huang-pi-qu-di-san-zhong-xue.md
        - 武汉市黄陂区第七中学: schools/wu-han-shi-huang-pi-qu-di-qi-zhong-xue.md
        - 武汉市黄陂区第六中学: schools/wu-han-shi-huang-pi-qu-di-liu-zhong-xue.md
        - 武汉市黄陂区第一中学: schools/wu-han-shi-huang-pi-qu-di-yi-zhong-xue.md
        - 武汉市汉口北高级中学: schools/wu-han-shi-han-kou-bei-gao-ji-zhong-xue.md
        - 武汉康礼高级中学有限公司: schools/wu-han-kang-li-gao-ji-zhong-xue-you-xian-gong-si.md
        - 武汉市新洲区第一中学: schools/wu-han-shi-xin-zhou-qu-di-yi-zhong-xue.md
        - 武汉市新洲区第二中学: schools/wu-han-shi-xin-zhou-qu-di-er-zhong-xue.md
        - 武汉市新洲区第三中学: schools/wu-han-shi-xin-zhou-qu-di-san-zhong-xue.md
        - 武汉市新洲区第四中学: schools/wu-han-shi-xin-zhou-qu-di-si-zhong-xue.md
        - 武汉市新洲区城关高级中学: schools/wu-han-shi-xin-zhou-qu-cheng-guan-gao-ji-zhong-xue.md
        - 武汉市新洲区阳逻高级中学: schools/wu-han-shi-xin-zhou-qu-yang-luo-gao-ji-zhong-xue.md
extra_css:
  - extra.css
  - https://fontsapi.zeoseven.com/292/main/result.css
hooks:
  - docs/overrides/hooks/reading_time.py    # 阅读时间统计
copyright: Copyright &copy; 2025~2025 619&vic2349 # 左下角的版权声明